
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 118
#define YY_END_OF_BUFFER 119
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[426] =
    {   0,
        0,    0,  119,  117,  115,  116,   99,  117,  105,   98,
      117,   93,   94,  103,  102,   90,  101,   97,  104,   54,
       54,   91,   87,  106,   92,  107,  110,   51,   51,   95,
      117,   96,  108,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       88,  109,   89,  100,  114,   85,    0,   63,    0,   71,
       89,   80,   72,    0,   56,    0,   69,   77,   67,   78,
       68,   79,    0,   58,   70,   59,   53,    0,   54,    0,
       54,   86,   96,   88,   95,   76,   82,   84,   83,   75,
       51,    0,    0,    0,    0,    0,   73,   51,   51,   51,

       51,   51,   51,   51,   51,   51,   51,   51,   51,   15,
       51,   51,   51,   51,   51,   51,   51,   24,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   74,   81,  114,  114,  114,  114,   64,
        0,   58,   58,   58,    0,   59,   59,   53,    0,   57,
        0,   52,   66,   65,    0,    0,    0,   55,    0,    0,
        0,   51,   51,   51,   51,    2,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       22,   51,   51,   27,   51,   51,   30,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,

       51,   51,   51,   51,   51,  114,  114,  114,    0,   58,
        0,   58,   58,    0,   59,   57,   57,    0,    0,   52,
        0,    0,    0,    0,    0,   51,   51,   51,   51,    3,
       51,    6,    7,   51,   51,   51,   51,   51,   51,   51,
       18,   19,   51,   51,   23,   51,   28,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   48,   51,   51,  114,  114,  114,    0,
       58,    0,    0,    0,   62,    0,    0,    0,    0,    4,
       51,   51,   51,    5,    8,   10,   51,   51,   51,   51,
       51,   51,   21,   51,   51,   51,   51,   51,   51,   35,

       51,   51,   51,   51,   51,   51,   51,   51,   45,   51,
       47,   51,   50,  114,  114,  114,    0,   60,    0,   61,
       62,   62,    0,    0,    0,   51,   51,   51,   51,   51,
       51,   51,   14,   16,   51,   20,   26,   51,   51,   51,
       51,   34,   36,   37,   38,   40,   41,   51,   51,   51,
       51,   51,  114,  113,  114,   60,   60,   61,   61,    0,
        0,   51,   51,   51,   51,   51,   13,   51,   51,   51,
       51,   51,   51,   51,   43,   51,   51,   51,  112,  113,
      114,    0,    0,    9,   51,    1,   51,   12,   51,   51,
       31,   51,   33,   51,   42,   44,   46,   49,  112,  111,

        0,    0,   51,   51,   51,   29,   51,   51,  111,    0,
       25,   11,   51,   51,   51,   51,   51,   39,   17,   51,
       51,   51,   51,   32,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   29,   27,   30,   31,
       32,   32,   33,   32,   32,   34,   32,   32,   32,   35,
       32,   32,   32,   32,   36,   32,   32,   37,   32,   32,
       38,   39,   40,   41,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   32,   52,   53,   54,   55,
       56,   57,   32,   58,   59,   60,   61,   62,   63,   64,
       65,   66,   67,   68,   69,   70,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[71] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    1,    4,    4,
        1,    1,    1,    1,    1,    1,    4,    4,    4,    4,
        4,    5,    5,    5,    5,    5,    5,    1,    5,    1,
        1,    5,    4,    4,    4,    4,    4,    4,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[458] =
    {   0,
        0,  868,  874,  876,  876,  876,  849,   65,   48,   65,
       66,  876,  876,  848,   61,  876,   62,   60,  847,   89,
       77,   63,  876,   91,  846,   57,  876,  830,   92,  876,
       55,  876,  844,  104,   61,   71,  101,  100,  106,   96,
       62,  116,   78,  119,   56,  124,  121,  130,  134,  128,
      876,   59,  876,  876,  126,  876,  142,  876,  864,  876,
      876,  876,  876,   82,  876,  863,  876,  876,  876,  876,
      876,  876,  848,  172,  876,  179,  188,  181,  178,  847,
      217,  876,  876,  876,  876,  839,  876,  876,  876,  838,
      822,  160,  176,  178,    0,    0,  876,  137,  155,  189,

      190,  194,  201,  133,  203,  207,  213,  205,  206,  216,
      218,  224,  219,  226,  228,  227,  229,  821,  235,  232,
      236,  230,  243,  240,  242,  258,  165,  259,  260,  261,
      267,  268,  271,  876,  876,    0,  813,  807,  799,  876,
      295,  805,  876,  304,  311,  804,  876,  292,  285,  313,
        0,  324,  876,  876,    0,    0,  326,  876,  851,    0,
        0,  290,  300,  233,  301,  814,  311,  329,  309,  324,
      310,  331,  332,  337,  298,  335,  340,  334,  347,  350,
      813,  341,  344,  812,  353,  357,  811,  359,  360,  361,
      362,  364,  369,  366,  367,  368,  370,  375,  372,  377,

      386,  373,  392,  396,  381,  802,  793,  804,  398,  421,
      428,  795,  876,  426,  430,  794,  876,  401,  408,  423,
      466,    0,    0,    0,    0,  414,  431,  417,  424,  805,
       89,  804,  803,  412,  415,  438,  429,  434,  448,  452,
      802,  801,  453,  454,  800,  457,  799,  456,  458,  459,
      460,  463,  464,  461,  466,  465,  468,  481,  470,  486,
      488,  489,  490,  798,  471,  495,  781,  788,  785,  516,
      525,  532,  541,  530,  534,    0,    0,    0,    0,  794,
      494,  519,  524,  793,  792,   51,  525,  528,  527,  532,
      533,  536,  791,  547,  538,  523,  549,  550,  551,  790,

      491,  554,  553,  558,  560,  561,  564,  566,  789,  568,
      788,  569,  787,  765,  822,  769,  593,  595,  597,  602,
      771,  876,    0,    0,    0,  782,  580,  585,  586,  592,
      591,  596,  781,  780,  593,  779,  778,  602,  595,  600,
      612,  777,  776,  775,  605,  774,  773,  610,  615,  620,
      621,  622,  809,    0,  767,  758,  876,  757,  876,    0,
        0,  623,  626,  625,  633,  632,  768,  638,  639,  627,
      634,  642,  643,  647,  767,  650,  644,  653,    0,    0,
      803,    0,    0,  765,  654,  764,  656,  763,  659,  660,
      762,  662,  761,  666,  760,  759,  758,  757,    0,    0,

        0,    0,  657,  664,  667,  756,  669,  672,    0,    0,
      755,  754,  674,  675,  678,  679,  684,  753,  752,  680,
      689,  682,  688,  751,  876,  748,  753,  755,  760,  763,
      767,  785,  784,  780,  775,  770,  758,  743,  742,  741,
      740,  739,  738,  736,  733,  732,  730,  726,  725,  772,
      536,  458,  777,  456,  422,  782,  339
    } ;

static const flex_int16_t yy_def[458] =
    {   0,
      425,    1,  425,  425,  425,  425,  425,  426,  425,  425,
      427,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  428,  428,  425,
      425,  425,  425,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      425,  425,  425,  425,  429,  425,  426,  425,  426,  425,
      425,  425,  425,  427,  425,  427,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  430,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      428,  425,  426,  431,  432,  433,  425,  428,  428,  428,

      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  425,  425,  429,  429,  429,  429,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      434,  430,  425,  425,  435,  436,  431,  425,  431,  437,
      438,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,

      428,  428,  428,  428,  428,  429,  429,  429,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  434,  434,  425,
      425,  439,  440,  441,  442,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  429,  429,  429,  425,
      425,  425,  425,  425,  425,  443,  444,  445,  446,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,

      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  429,  429,  429,  425,  425,  425,  425,
      425,  425,  447,  448,  449,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  429,  450,  429,  425,  425,  425,  425,  451,
      452,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  453,  450,
      429,  454,  455,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  453,  456,

      457,  446,  428,  428,  428,  428,  428,  428,  456,  448,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,    0,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425
    } ;

static const flex_int16_t yy_nxt[947] =
    {   0,
        4,    5,    6,    5,    7,    8,    4,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   28,   28,   28,
       28,   28,   28,   29,   28,   28,   28,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   28,
       42,   28,   43,   28,   44,   28,   28,   45,   46,   47,
       48,   49,   50,   28,   28,   28,   51,   52,   53,   54,
       58,   60,   61,   62,   68,   65,   73,   70,   74,   74,
       89,   90,  134,   82,   69,   71,   72,   83,   63,   92,
       95,   65,  330,   76,   92,   81,   81,   93,   84,   92,

       92,   94,  123,   59,   66,   76,   78,   77,   77,   92,
       79,   85,   79,   86,   87,   96,   92,  117,   78,  102,
       66,  103,   79,   78,   79,   80,  135,   92,  104,   79,
       92,   98,   99,  120,   92,   78,  100,   79,   92,   92,
      284,   79,   92,  105,   92,  101,  109,   58,  115,   79,
      106,  116,   80,  107,   92,  110,  108,   92,  112,   92,
      113,  121,   92,  118,  111,  122,   92,  128,   92,  114,
      119,   92,   92,  124,  125,   92,  137,  133,  138,  168,
       59,   58,  139,  126,  130,  129,  127,  158,  131,  132,
       74,   74,  162,   92,  149,  155,  149,  144,  144,  150,

      150,  141,  142,   92,   76,  142,   77,   77,  145,  146,
      163,   79,  146,   79,   59,  197,  159,   78,  141,  142,
      156,  148,  143,  148,  142,  145,  146,   92,   92,  147,
       79,  146,   92,   76,   78,   81,   81,  165,   79,   92,
      148,   92,  164,   92,   92,   92,   78,  166,  148,  170,
       79,   92,   79,  173,   92,  171,   92,   92,  174,  172,
      167,  169,   92,   78,   92,   92,   92,   92,   92,   79,
       92,   92,  176,   92,   92,  228,  175,   79,   92,  178,
       92,   92,  177,  180,  181,  179,  185,  183,  182,  186,
      193,  188,  187,  189,  184,  192,   92,   92,   92,   92,

      195,  190,  191,  150,  150,   92,   92,  194,  209,   92,
      209,  200,  198,  210,  210,  196,  199,  202,  203,  201,
      204,  205,  144,  144,  214,  148,  214,  148,   92,  215,
      215,  150,  150,  211,  212,  158,   92,  212,   92,   92,
      219,  239,  410,  216,  148,  226,  216,   92,   92,   92,
      211,  212,  148,  227,  213,  232,  212,  220,  221,  220,
      216,  229,   92,  217,  159,  216,  230,   92,  234,   92,
       92,  231,   92,   92,  237,   92,  220,  240,   92,   92,
      221,  233,   92,  238,  220,   92,  241,  242,   92,  235,
      236,   92,  244,  243,  246,   92,  245,   92,   92,   92,

       92,  247,   92,  248,   92,   92,   92,   92,   92,  249,
       92,   92,  255,   92,  250,   92,  210,  210,  260,   92,
      251,  253,  252,  254,   92,  402,  256,  263,  257,  258,
       92,  259,  261,  266,   92,  272,  262,  264,  265,  210,
      210,  270,  273,  270,  215,  215,  271,  271,  215,  215,
       92,  142,   92,   92,  142,   92,  220,  272,  220,  401,
      146,  383,   92,  146,  273,  282,  280,   92,  142,   92,
      285,  143,   92,  142,  286,  220,   92,  146,  283,  274,
      147,  274,  146,  220,  275,  275,   92,  281,  287,  288,
       92,   92,   92,  289,   92,   92,   92,   92,   92,   92,

      290,   92,   92,   92,   92,  291,   92,  301,   92,   92,
      292,  294,  304,  293,  295,  303,  296,  298,  297,   92,
      299,  302,  306,  300,   92,  305,   92,   92,   92,   92,
      312,  307,   92,   92,  271,  271,  343,  310,  311,  382,
      308,  313,  309,  271,  271,  317,  327,  317,  275,  275,
      318,  318,  275,  275,  319,  212,  319,   92,  212,  320,
      320,   92,   92,   92,  321,   92,   92,  321,  329,  328,
       92,   92,  212,  333,   92,  213,   92,  212,  334,  331,
      332,  321,  339,  335,  322,   92,  321,   92,   92,   92,
      336,   92,   92,  337,  338,  340,   92,  345,   92,   92,

      341,  344,   92,  348,   92,  342,   92,   92,  350,  347,
      349,  318,  318,  318,  318,  320,  320,  346,   92,  352,
      320,  320,  351,   92,   92,  356,  362,  364,  356,   92,
       92,   92,  358,   92,   92,  358,  365,  368,   92,  363,
       92,  370,  356,   92,  369,  357,  373,  356,   92,  358,
       92,  366,  359,   92,  358,  367,  372,  371,   92,   92,
       92,   92,  375,   92,   92,   92,  386,  377,  385,  374,
       92,   92,   92,  376,  378,  387,   92,   92,  388,  389,
       92,   92,   92,  390,  391,   92,  384,  394,   92,  397,
      392,   92,   92,  395,   92,   92,  396,   92,   92,  398,

       92,  393,   92,  405,   92,   92,  406,   92,  408,  413,
       92,  403,   92,   92,  404,  414,   92,   92,   92,  407,
       92,  411,   92,  412,  421,  420,   92,   92,  361,   91,
      415,  422,  416,  360,  417,  326,  325,  418,  419,  324,
      423,  323,  279,  278,  277,  276,  225,  424,   57,   57,
       57,   57,   57,   64,   64,   64,   64,   64,   91,   91,
      136,  224,  136,  136,  136,  152,  152,  157,  157,  157,
      157,  157,  380,  223,  380,  380,  380,  399,  222,  399,
      399,  399,  409,  218,  409,  409,  409,  161,  160,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   92,   92,

       92,   92,   92,   92,  400,   92,   92,  359,  357,  381,
      379,   92,   92,   92,   92,   92,   92,   92,   92,   92,
       92,  322,  355,  354,  353,   92,   92,   92,   92,   92,
       92,   92,   92,  316,  315,  314,   92,   92,   92,   92,
       92,   92,   92,   92,  217,  213,  269,  268,  267,   92,
       92,   92,   92,  425,  147,  143,  208,  207,  206,   92,
       92,  154,  153,  151,  140,  425,  425,   97,   92,   88,
       75,   67,   56,  425,   55,    3,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,

      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425
    } ;

static const flex_int16_t yy_chk[947] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        8,    9,    9,   10,   15,   11,   18,   17,   18,   18,
       26,   26,   52,   22,   15,   17,   17,   22,   10,  286,
       31,   64,  286,   21,   45,   21,   21,   29,   24,   35,

       41,   29,   45,    8,   11,   20,   21,   20,   20,   36,
       21,   24,   21,   24,   24,   31,   43,   41,   20,   35,
       64,   35,   20,   21,   20,   20,   52,  231,   36,   21,
       29,   34,   34,   43,   40,   20,   34,   21,   38,   37,
      231,   20,   34,   37,   39,   34,   38,   57,   40,   20,
       37,   40,   20,   37,   42,   38,   37,   44,   39,   47,
       39,   44,   46,   42,   38,   44,   50,   47,   48,   39,
       42,  104,   49,   46,   46,   98,   55,   50,   55,  104,
       57,   93,   55,   46,   48,   47,   46,   94,   48,   49,
       74,   74,   98,   99,   78,   92,   78,   76,   76,   78,

       78,   74,   74,  127,   77,   74,   77,   77,   76,   76,
       99,   79,   76,   79,   93,  127,   94,   77,   74,   74,
       92,   77,   74,   77,   74,   76,   76,  100,  101,   76,
       79,   76,  102,   81,   77,   81,   81,  101,   79,  103,
       77,  105,  100,  108,  109,  106,   81,  102,   77,  106,
       81,  107,   81,  109,  110,  107,  111,  113,  109,  108,
      103,  105,  112,   81,  114,  116,  115,  117,  122,   81,
      120,  164,  111,  119,  121,  164,  110,   81,  124,  113,
      125,  123,  112,  115,  116,  114,  120,  119,  117,  121,
      125,  123,  122,  123,  119,  124,  126,  128,  129,  130,

      126,  123,  123,  149,  149,  131,  132,  125,  141,  133,
      141,  130,  128,  141,  141,  126,  129,  131,  132,  130,
      132,  133,  144,  144,  145,  148,  145,  148,  162,  145,
      145,  150,  150,  144,  144,  157,  175,  144,  163,  165,
      152,  175,  457,  150,  148,  162,  150,  169,  171,  167,
      144,  144,  148,  163,  144,  169,  144,  152,  152,  152,
      150,  165,  170,  150,  157,  150,  167,  168,  171,  172,
      173,  168,  178,  176,  173,  174,  152,  176,  177,  182,
      152,  170,  183,  174,  152,  179,  177,  178,  180,  172,
      172,  185,  180,  179,  183,  186,  182,  188,  189,  190,

      191,  185,  192,  186,  194,  195,  196,  193,  197,  188,
      199,  202,  194,  198,  189,  200,  209,  209,  199,  205,
      190,  192,  191,  193,  201,  455,  195,  202,  196,  197,
      203,  198,  200,  205,  204,  218,  201,  203,  204,  210,
      210,  211,  219,  211,  214,  214,  211,  211,  215,  215,
      234,  210,  226,  235,  210,  228,  220,  218,  220,  454,
      215,  452,  229,  215,  219,  228,  226,  237,  210,  227,
      234,  210,  238,  210,  235,  220,  236,  215,  229,  221,
      215,  221,  215,  220,  221,  221,  239,  227,  236,  237,
      240,  243,  244,  238,  248,  246,  249,  250,  251,  254,

      239,  252,  253,  256,  255,  240,  257,  254,  259,  265,
      243,  246,  257,  244,  248,  256,  249,  251,  250,  258,
      252,  255,  259,  253,  260,  258,  261,  262,  263,  301,
      265,  260,  281,  266,  270,  270,  301,  262,  263,  451,
      260,  266,  261,  271,  271,  272,  281,  272,  274,  274,
      272,  272,  275,  275,  273,  271,  273,  282,  271,  273,
      273,  296,  283,  287,  275,  289,  288,  275,  283,  282,
      290,  291,  271,  289,  292,  271,  295,  271,  290,  287,
      288,  275,  296,  291,  275,  294,  275,  297,  298,  299,
      292,  303,  302,  294,  295,  297,  304,  303,  305,  306,

      298,  302,  307,  306,  308,  299,  310,  312,  308,  305,
      307,  317,  317,  318,  318,  319,  319,  304,  327,  312,
      320,  320,  310,  328,  329,  318,  327,  329,  318,  331,
      330,  335,  320,  339,  332,  320,  330,  335,  340,  328,
      338,  339,  318,  345,  338,  318,  345,  318,  348,  320,
      341,  331,  320,  349,  320,  332,  341,  340,  350,  351,
      352,  362,  349,  364,  363,  370,  364,  351,  363,  348,
      366,  365,  371,  350,  352,  365,  368,  369,  366,  368,
      372,  373,  377,  369,  370,  374,  362,  373,  376,  377,
      371,  378,  385,  374,  387,  403,  376,  389,  390,  378,

      392,  372,  404,  389,  394,  405,  390,  407,  394,  405,
      408,  385,  413,  414,  387,  407,  415,  416,  420,  392,
      422,  403,  417,  404,  420,  417,  423,  421,  449,  448,
      408,  421,  413,  447,  414,  446,  445,  415,  416,  444,
      422,  443,  442,  441,  440,  439,  438,  423,  426,  426,
      426,  426,  426,  427,  427,  427,  427,  427,  428,  428,
      429,  437,  429,  429,  429,  430,  430,  431,  431,  431,
      431,  431,  450,  436,  450,  450,  450,  453,  435,  453,
      453,  453,  456,  434,  456,  456,  456,  433,  432,  424,
      419,  418,  412,  411,  406,  398,  397,  396,  395,  393,

      391,  388,  386,  384,  381,  375,  367,  358,  356,  355,
      353,  347,  346,  344,  343,  342,  337,  336,  334,  333,
      326,  321,  316,  315,  314,  313,  311,  309,  300,  293,
      285,  284,  280,  269,  268,  267,  264,  247,  245,  242,
      241,  233,  232,  230,  216,  212,  208,  207,  206,  187,
      184,  181,  166,  159,  146,  142,  139,  138,  137,  118,
       91,   90,   86,   80,   73,   66,   59,   33,   28,   25,
       19,   14,    7,    3,    2,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,

      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "./scan.l"
#line 2 "./scan.l"
/*	$Id: scan.l,v 1.11 2020/02/02 09:52:32 ragge Exp $	*/

/*
 * Copyright (c) 2002 Anders Magnusson. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#line 825 "lex.yy.c"
#line 42 "./scan.l"
#include <stdlib.h>
#include <errno.h>  
#include <string.h>
#include <stdarg.h>
#include <ctype.h>

#include "pass1.h"
#include "cgram.h"

#define bdebug flexbdebug

static NODE *cvtdig(int radix);
static NODE *charcon(void);
static NODE *wcharcon(void);
static void control(int);
static void pragma(void);
int notype, parbal, inattr, parlvl, nodinit, inoso;
static int dotfile;
static int resw(TWORD, int);
static int namechk(void);

#define	CPP_IDENT 	2
#define	CPP_LINE 	3
#define	CPP_HASH	4

#ifdef STABS
#define	STABS_LINE(x) if (gflag && cftnsp) stabs_line(x)
#else
#define STABS_LINE(x)
#endif
#if defined(FLEX_SCANNER) && YY_FLEX_SUBMINOR_VERSION == 31
/* Hack to avoid unnecessary warnings */
FILE *yyget_in  (void);
FILE *yyget_out  (void);
int yyget_leng  (void);
char *yyget_text  (void);
void yyset_in (FILE *);
void yyset_out (FILE *);
int yyget_debug  (void);
void yyset_debug (int);
int yylex_destroy  (void);
extern int yyget_lineno (void);
extern void yyset_lineno (int);
#endif

#line 872 "lex.yy.c"
#line 873 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 89 "./scan.l"


#line 1096 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 426 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 876 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 91 "./scan.l"
{
				if (cftnsp == NULL)
					uerror("__func__ outside function");
				yylval.strp = cftnsp->sname; /* XXX - not C99 */
				return(C_STRING);
			}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 97 "./scan.l"
{ return(C_ASM); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 98 "./scan.l"
{ 	return resw(AUTO, C_CLASS); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 99 "./scan.l"
{ 	return resw(BOOL, C_TYPE); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 100 "./scan.l"
{ return(C_BREAK); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 101 "./scan.l"
{ return(C_CASE); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 102 "./scan.l"
{ 	return resw(CHAR, C_TYPE); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 103 "./scan.l"
{ yylval.intval = CLNAME; notype=1; return(C_STRUCT); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 104 "./scan.l"
{ 	return resw(COMPLEX, C_TYPE); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 105 "./scan.l"
{ 	return resw(CON, C_QUALIFIER); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 106 "./scan.l"
{ yylval.intval = CONST_CAST; return(CXX_CASTS); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 107 "./scan.l"
{ return(C_CONTINUE); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 108 "./scan.l"
{ return(C_DEFAULT); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 109 "./scan.l"
{ return(CXX_DELETE); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 110 "./scan.l"
{ return(C_DO); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 111 "./scan.l"
{ 	return resw(DOUBLE, C_TYPE); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 112 "./scan.l"
{ yylval.intval = DYN_CAST; return(CXX_CASTS); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 113 "./scan.l"
{ return(C_ELSE); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 114 "./scan.l"
{ notype=1; return(C_ENUM); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 115 "./scan.l"
{ 	return resw(EXTERN, C_CLASS); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 116 "./scan.l"
{ 	return resw(FLOAT, C_TYPE); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 117 "./scan.l"
{ return(C_FOR); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 118 "./scan.l"
{ notype=1; return(C_GOTO); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 119 "./scan.l"
{ return(C_IF); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 120 "./scan.l"
{ 	return resw(IMAG, C_TYPE); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 121 "./scan.l"
{ return(C_FUNSPEC); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 122 "./scan.l"
{ 	return resw(INT, C_TYPE); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 123 "./scan.l"
{ 	return resw(LONG, C_TYPE); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 124 "./scan.l"
{ 	return(CXX_NAMESPACE); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 125 "./scan.l"
{ 	notype = 0; return(CXX_NEW); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 126 "./scan.l"
{ 	return resw(REGISTER, C_CLASS); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 127 "./scan.l"
{ yylval.intval = REINT_CAST; return(CXX_CASTS); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 128 "./scan.l"
{ ; /* just ignore */ }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 129 "./scan.l"
{ return(C_RETURN); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 130 "./scan.l"
{ 	return resw(SHORT, C_TYPE); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 131 "./scan.l"
{ 	return resw(SIGNED, C_TYPE); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 132 "./scan.l"
{ return(C_SIZEOF); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 133 "./scan.l"
{ 	return resw(STATIC, C_CLASS); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 134 "./scan.l"
{ yylval.intval = STATIC_CAST; return(CXX_CASTS); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 135 "./scan.l"
{ yylval.intval = STNAME; notype=1; return(C_STRUCT); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 136 "./scan.l"
{ return(C_SWITCH); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 137 "./scan.l"
{ return(CXX_TEMPLATE); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 138 "./scan.l"
{ 	return resw(TYPEDEF, C_CLASS); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 139 "./scan.l"
{ return(CXX_TYPENAME); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 140 "./scan.l"
{ yylval.intval = UNAME; notype=1; return(C_STRUCT); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 141 "./scan.l"
{ 	return resw(UNSIGNED, C_TYPE); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 142 "./scan.l"
{ return(CXX_USING); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 143 "./scan.l"
{ 	return resw(VOID, C_TYPE); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 144 "./scan.l"
{	return resw(VOL, C_QUALIFIER); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 145 "./scan.l"
{ return(C_WHILE); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 147 "./scan.l"
{ return namechk(); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 148 "./scan.l"
{ yylval.nodep = cvtdig(16); return(C_ICON); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 149 "./scan.l"
{ yylval.nodep = cvtdig(8); return(C_ICON); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 150 "./scan.l"
{ yylval.nodep = cvtdig(10); return(C_ICON); }
	YY_BREAK
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 151 "./scan.l"
{ yylval.nodep = wcharcon(); return(C_ICON); }
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 152 "./scan.l"
{ yylval.nodep = charcon(); return(C_ICON); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 154 "./scan.l"
{ yylval.nodep = floatcon(yytext); return(C_FCON); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 155 "./scan.l"
{ yylval.nodep = floatcon(yytext); return(C_FCON); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 156 "./scan.l"
{ yylval.nodep = floatcon(yytext); return(C_FCON); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 157 "./scan.l"
{ yylval.nodep = fhexcon(yytext); return(C_FCON); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 158 "./scan.l"
{ yylval.nodep = fhexcon(yytext); return(C_FCON); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 159 "./scan.l"
{ yylval.nodep = fhexcon(yytext); return(C_FCON); }
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 161 "./scan.l"
{ yylval.strp = yytext; return C_STRING; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 163 "./scan.l"
{ return(C_ELLIPSIS); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 164 "./scan.l"
{ yylval.intval = RSEQ; return(C_ASOP); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 165 "./scan.l"
{ yylval.intval = LSEQ; return(C_ASOP); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 166 "./scan.l"
{ yylval.intval = PLUSEQ; return(C_ASOP); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 167 "./scan.l"
{ yylval.intval = MINUSEQ; return(C_ASOP); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 168 "./scan.l"
{ yylval.intval = MULEQ; return(C_ASOP); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 169 "./scan.l"
{ yylval.intval = DIVEQ; return(C_ASOP); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 170 "./scan.l"
{ yylval.intval = MODEQ; return(C_ASOP); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 171 "./scan.l"
{ yylval.intval = ANDEQ; return(C_ASOP); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 172 "./scan.l"
{ yylval.intval = EREQ; return(C_ASOP); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 173 "./scan.l"
{ yylval.intval = OREQ; return(C_ASOP); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 174 "./scan.l"
{ yylval.intval = RS; return(C_SHIFTOP); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 175 "./scan.l"
{ yylval.intval = LS; return(C_SHIFTOP); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 176 "./scan.l"
{ yylval.intval = INCR; return(C_INCOP); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 177 "./scan.l"
{ yylval.intval = DECR; return(C_INCOP); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 178 "./scan.l"
{ yylval.intval = STREF; return(C_STROP); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 179 "./scan.l"
{ yylval.intval = ANDAND; return(C_ANDAND); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 180 "./scan.l"
{ yylval.intval = OROR; return(C_OROR); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 181 "./scan.l"
{ yylval.intval = LE; return(C_RELOP); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 182 "./scan.l"
{ yylval.intval = GE; return(C_RELOP); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 183 "./scan.l"
{ yylval.intval = EQ; return(C_EQUOP); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 184 "./scan.l"
{ yylval.intval = NE; return(C_EQUOP); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 185 "./scan.l"
{ return(CXX_DUALCC); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 186 "./scan.l"
{ notype = 0; return(';'); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 187 "./scan.l"
{ notype = 0; return('{'); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 188 "./scan.l"
{ if (rpole) notype = 1; return('}'); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 189 "./scan.l"
{ if (parbal && !inoso) notype = 0; return(','); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 190 "./scan.l"
{ if (doing_init) nodinit--; return(':'); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 191 "./scan.l"
{ return('='); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 192 "./scan.l"
{ parbal++; notype = 0; return('('); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 193 "./scan.l"
{	parbal--;
				inoso = 0;
				if (parbal==0) { notype = 0; }
				if (inattr && parlvl == parbal)
					inattr = 0;
				return(')'); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 199 "./scan.l"
{ return('['); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 200 "./scan.l"
{ return(']'); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 201 "./scan.l"
{ yylval.intval = DOT; return(C_STROP); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 202 "./scan.l"
{ return('&'); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 203 "./scan.l"
{ yylval.intval = NOT; return(C_UNOP); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 204 "./scan.l"
{ yylval.intval = COMPL; return(C_UNOP); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 205 "./scan.l"
{ return('-'); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 206 "./scan.l"
{ return('+'); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 207 "./scan.l"
{ if (parbal && notype == 0) notype = 1; return('*'); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 208 "./scan.l"
{ yylval.intval = DIV; return(C_DIVOP); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 209 "./scan.l"
{ yylval.intval = MOD; return(C_DIVOP); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 210 "./scan.l"
{ yylval.intval = LT; return(C_RELOP); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 211 "./scan.l"
{ yylval.intval = GT; return(C_RELOP); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 212 "./scan.l"
{ return('^'); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 213 "./scan.l"
{ return('|'); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 214 "./scan.l"
{ if (doing_init) nodinit++; return('?'); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 215 "./scan.l"
{ pragma(); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 216 "./scan.l"
{ control(CPP_IDENT); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 217 "./scan.l"
{ control(CPP_LINE); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 218 "./scan.l"
{ control(CPP_HASH); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 220 "./scan.l"
{ }
	YY_BREAK
case 116:
/* rule 116 can match eol */
YY_RULE_SETUP
#line 221 "./scan.l"
{ ++lineno; STABS_LINE(lineno); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 222 "./scan.l"
{ /* ignore bad characters */ }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 224 "./scan.l"
ECHO;
	YY_BREAK
#line 1758 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 426 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 426 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 425);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 224 "./scan.l"


int issyshdr;
char *ftitle = "<stdin>";

static int
namechk(void)
{ 	
	struct symtab *s;
	int i;

	yylval.strp = addname(yytext);

	while ((i = input()) == ' ' || i == '\t')
		;
	if (i == ':') {
		if ((i = input()) == ':')
			return CXX_MORENM;
		unput(i);
		if (doing_init && nodinit == 0)
			return(GCC_DESIG);
		i = ':';
	}
	unput(i);

#ifdef GCC_COMPAT
	if ((i = gcc_keyword(yylval.strp, &yylval.nodep)) > 0)
		return i;
#endif

	if (notype)
		return(C_NAME);
	s = lookup(yylval.strp, SNOCREAT);
	return s && s->sclass == TYPEDEF ?  notype=1, C_TYPENAME : C_NAME;
}

int
yywrap(void)
{
	if (0) unput(0); /* quiet gcc */
	return(1);
}

int
resw(TWORD t, int rv)
{
	if (inattr) {
		yylval.strp = addname(yytext);
		return C_NAME;
	}

	switch (rv) {
	case C_CLASS:
		yylval.nodep = block(CLASS, NIL, NIL, t, 0, 0);
		return rv;

	case C_QUALIFIER:
		yylval.nodep = block(QUALIFIER, NIL, NIL, 0, 0, 0);
		yylval.nodep->n_qual = t;
		return rv;

	case C_TYPE:
		yylval.nodep = mkty(t, 0, 0);
		notype=1;
		return(rv);

	default:
		cerror("resw");
	}
	return 0;
}

#ifndef SOFTFLOAT

static long double
typround(long double dc, char *e, TWORD *tw)
{
	int im = 0;

	*tw = DOUBLE;
	for (; *e; e++) {
		switch (*e) {
		case 'f':
		case 'F':
			*tw = FLOAT;
			dc = (float)dc;
			break;
		case 'l':
		case 'L':
			*tw = LDOUBLE;
			break;
		case 'i':
		case 'I':
			im = 1;
			break;
		}
	}
	if (*tw == DOUBLE)
		dc = (double)dc;
#ifndef NO_COMPLEX
	if (im)
		*tw += (FIMAG-FLOAT);
#endif
	return dc;
}

/*
 * XXX floatcon() and fhexcon() should be in support libraries for
 * the target floating point.
 */
static NODE *
f2(char *str)
{
	TWORD tw;
	NODE *p;
	long double dc;
	char *eptr;

#ifdef HAVE_STRTOLD
	dc = strtold(str, &eptr); /* XXX - avoid strtod() */
#else
	dc = strtod(str, &eptr); /* XXX - avoid strtod() */
#endif
	dc = typround(dc, eptr, &tw);
	p = block(FCON, NIL, NIL, tw, 0, 0);
	p->n_dcon = fltallo();
	FCAST(p->n_dcon)->fp = dc;
	return p;
}

NODE *
floatcon(char *s)
{
	return f2(s);
}

static int
h2n(int ch)
{
	if (ch >= '0' && ch <= '9')
		return ch - '0';
	if (ch >= 'a' && ch <= 'f')
		return ch - 'a' + 10;
	return ch - 'A' + 10;
	
}

NODE *
fhexcon(char *c)
{
	TWORD tw;
	char *ep;
	long double d;
	int i, ed;
	NODE *p;

	d = 0.0;
	ed = 0;
	c+= 2; /* skip 0x */
#define FSET(n) { d *= 2; if (i & n) d += 1.0; }
	for (; *c != '.' && *c != 'p' && *c != 'P'; c++) {
		i = h2n(*c);
		FSET(8); FSET(4); FSET(2); FSET(1);
	}
	if (*c != '.' && *c != 'p' && *c != 'P')
		cerror("fhexcon");
	if (*c == '.') {
		c++;
		for (; *c != 'p' && *c != 'P'; c++) {
			i = h2n(*c);
			FSET(8); FSET(4); FSET(2); FSET(1);
			ed -= 4;
		}
	}
	if (*c != 'P' && *c != 'p')
		cerror("fhexcon2");
	c++;
	ed += (int)strtol(c, &ep, 10);

	/* avoid looping in vain. Idea from Fred J. Tydeman */
	if (ed > 32769) ed = 32769;
	if (ed < -32769) ed = -32769;

	while (ed > 0)
		d *= 2, ed--;
	while (ed < 0)
		d /= 2, ed++;
	d = typround(d, ep, &tw);
	p = block(FCON, NIL, NIL, tw, 0, 0);
	p->n_dcon = fltallo();
	FCAST(p->n_dcon)->fp = d;
	return p;
}
#endif

unsigned int
esccon(char **sptr)
{
	char *wr = *sptr;
	char *owr;
	char c;
	unsigned int val;
	int wsz = 4, esccon_warn = 1;

	switch (*wr++) {
	case 'a': val = '\a'; break;
	case 'b': val = '\b'; break;
	case 'f': val = '\f'; break;
	case 'n': val = '\n'; break;
	case 'r': val = '\r'; break;
	case 't': val = '\t'; break;
	case 'v': val = '\v'; break;
	case '\"': val = '\"'; break;
	case 'x': val = (int)strtoul(wr, &wr, 16); break;
	/* ISO/IEC 9099:1999 (E) 6.4.3 */
	case 'U'|(char)0x80:
		esccon_warn = 0;
		/* FALLTHROUGH */
	case 'U':
		wsz = 8;
		/* FALLTHROUGH */
	case 'u':
		owr = wr;
		while (wr < (owr + wsz))
			if (*wr == '\0')
				break;
			else
				++wr;
		if (wr != (owr + wsz)) {
			/* incomplete */
			val = (int)strtoul(owr, &wr, 16);
		} else {
			c = owr[wsz];
			owr[wsz] = '\0'; /* prevent it from reading too much */
			val = (int)strtoul(owr, &wr, 16);
			owr[wsz] = c;
		}
		if (wr != (owr + wsz))
			werror("incomplete universal character name");
		if (wsz == 4)
			val &= 0xFFFF;
		if (esccon_warn && ((val >= 0xD800 && val <= 0xDFFF) ||
		    (val < 0xA0 && val != 0x24 && val != 0x40 && val != 0x60)))
			werror("invalid universal character name %04X", val);
		break;
	case '0': case '1': case '2': case '3': case '4': 
	case '5': case '6': case '7':
		val = wr[-1] - '0';
		if (*wr >= '0' && *wr <= '7') {
			val = (val << 3) + (*wr++ - '0');
			if (*wr >= '0' && *wr <= '7')
				val = (val << 3) + (*wr++ - '0');
		}
		break;
	default: val = wr[-1];
	}
	*sptr = wr;
	return val;
}

NODE *
cvtdig(int radix)
{
	NODE *p;
	TWORD otype, ntype;
	unsigned long long v;
	char *ch = yytext;
	int n, numl, numu;

	if (radix == 16)
		ch += 2; /* Skip 0x */
	
	v = 0;
	while ((*ch >= '0' && *ch <= '9') || (*ch >= 'a' && *ch <= 'f') ||
	    (*ch >= 'A' && *ch <= 'F')) {
		v *= radix;
		n = *ch;
		n = (n <= '9' ? n - '0' : (n > 'F' ? n - 'a' : n - 'A') + 10);
		ch++;
		v += n;
	}
	/* Parse trailing chars */
	ntype = INT;
	numl = numu = 0;
	for (n = 0; n < 3; n++) {
		if (*ch == 0)
			break;
		if ((*ch == 'l' || *ch == 'L') && numl < 2)
			ntype+=2, numl++;
		else if ((*ch == 'u' || *ch == 'U') && numu < 1)
			ntype = ENUNSIGN(ntype), numu++;
		else
			break;
		ch++;
	}
	if (*ch)
		uerror("constant has too many '%c'", *ch);

	otype = ntype;
	switch (ntype) {
	case INT:
	case LONG:
	case LONGLONG:
		if (radix == 10) {
			if (otype == LONGLONG)
				break;
			if (v > MAX_LONG) { 
				ntype = LONGLONG;
				if (otype == LONG)
					break;
			} else if (v > MAX_INT)
				ntype = LONG;
		} else {
			if (v > MAX_LONGLONG) {
				ntype = ULONGLONG;
				if (otype == LONGLONG)
					break;
			} else if (v > MAX_ULONG) {
				ntype = LONGLONG;
			} else if (v > MAX_LONG) {
				ntype = ULONG;
				if (otype == LONG)
					break;
			} else if (v > MAX_UNSIGNED) {
				ntype = LONG;
			} else if (v > MAX_INT)
				ntype = UNSIGNED;
		}
		break;
	case UNSIGNED:
	case ULONG:
		if (v > MAX_ULONG) {
			ntype = ULONGLONG;
			if (otype == ULONG)
				break;
		} else if (v > MAX_UNSIGNED)
			ntype = ULONG;
		break;	
	}	

	ntype = ctype(ntype);
	p = xbcon(v, NULL, ntype);
	ASGLVAL(p->n_slval, v);

	return p;
}

/*
 * Convert a character constant to an integer.
 */
NODE *
charcon(void)
{
	int lastcon = 0;
	int val, i = 0;
	char *pp = yytext;

	pp++;	/* skip ' */
	while (*pp != '\'') {
		if (*pp++ == '\\') {
			val = esccon(&pp);
		} else
			val = pp[-1];
		makecc(val, i);
		i++;
	}

	if (i == 0)
		uerror("empty character constant");
	else if (i > (SZINT/SZCHAR) || (i>1))
		werror("too many characters in character constant");
	return bcon(lastcon);
}

NODE *
wcharcon(void)
{
	unsigned int lastcon = 0;
	unsigned int val, i = 0;
	char *pp = yytext;

	pp++;	/* skip L */
	pp++;	/* skip ' */
	while (*pp != '\'') {
		if (*pp++ == '\\') {
			val = esccon(&pp);
		} else
			val = pp[-1];
#if WCHAR_SIZE == 2
		lastcon = (lastcon << 16) | (val & 0xFFFF);
#else
		lastcon = val;
#endif
		i++;
	}

	if (i == 0)
		uerror("empty wide-character constant");
	else if (i > 1)
		werror("too many characters in wide-character constant");
	return xbcon(lastcon, NULL, ctype(UNSIGNED));
}

#ifndef MYDOTFILE
/*
 * Get basename and print it as '.file "basename.c"'
 */
static void
printdotfile(char *file)
{
	char *p;

	if ((p = strrchr(file, '/')) == NULL)
		p = file;
	else
		p++;
	printf(PRTPREF "\t.file \"%s\"\n", p);
}
#endif

void
control(int t)
{
	char *wr = yytext;
	char *eptr;
	int val;

	wr++;	/* Skip initial '#' */
	switch (t) {
	case CPP_IDENT:
		return;	/* Just skip these for now. */

	case CPP_LINE:
		wr += 4;
		/* FALLTHROUGH */
	case CPP_HASH:
		val = (int)strtol(wr, &eptr, 10);
		if (wr == eptr)	/* Illegal string */
			goto bad;
		wr = eptr;
		lineno = val - 1;
		while (*wr && *wr != '\"')
			wr++;
		if (*wr == 0)
			return;
		if (*wr++ != '\"')
			goto bad;
		eptr = wr;
		while (*wr && *wr != '\"')
			wr++;
		if (*wr != '\"')
			goto bad;
		*wr = 0;
		ftitle = addstring(eptr);
#ifdef STABS
		if (gflag)
			stabs_file(ftitle);
#endif
		if (dotfile == 0) {
			dotfile++;
			printdotfile(ftitle);
		}
	}
	return;
bad:
	werror("%s: illegal control", yytext);
}

int pragma_allpacked;
int pragma_packed, pragma_aligned;
char *pragma_renamed;

static int
pragmas_weak(char *str)
{
	struct symtab *sp;
	char *s1, *s2;

	if ((s1 = pragtok(NULL)) == NULL)
		return 1;
	if ((s2 = pragtok(NULL)) == NULL) {
		sp = lookup(addname(s1), SNORMAL);
#ifdef GCC_COMPAT
		sp->sap = attr_add(sp->sap, gcc_attr_parse(bdty(NAME, "weak")));
#else
		sp->sap = 0;
#endif
	} else if (*s2 == '=') {
		if ((s2 = pragtok(NULL)) == NULL)
			return 1;
		sp = lookup(addname(s2), SNORMAL);
#ifdef GCC_COMPAT
		sp->sap = attr_add(sp->sap, gcc_attr_parse(bdty(CALL,
		    bdty(NAME, "aliasweak"), bdty(STRING, s1, 0))));
#else
		sp->sap = NULL;
#endif
	} else
		return 1;
	return 0;
}

char *pragstore;

/* trivial tokenizer for pragmas */
#define ps pragstore
char *
pragtok(char *sin)
{
	static char ss[2];
	char *rv;

	if (sin)
		ps = sin;

	for (; isspace((int)*ps); ps++)
		;
	if (*ps == 0)
		return NULL;
	for (rv = ps; isalpha((int)*ps) || isdigit((int)*ps) || *ps == '_'; ps++)
		;
	ss[0] = *ps;
	if (rv == ps) {
		rv = ss, ps++;
	} else {
		*ps = 0;
		rv = tmpstrdup(rv);
		*ps = ss[0];
	}
	return rv;
}

/* return 1 on error */
int
eat(int ch)
{
	char *s = pragtok(0);
	return (s == 0 || *s != ch);
}

static int
pragmas_alpack(char *t)
{
	char *s;
	int ap;

	ap = (s = pragtok(0)) ? atoi(s) : 1;
	if (strcmp(t, "packed") == 0)
		pragma_packed = ap;
	else
		pragma_aligned = ap;
	return 0;
}


/*
 * Packing control.
 * still missing push/pop.
 */
static int
pragmas_pack(char *t)
{
	char *s;

	if (eat('('))
		return 1;
	s = pragtok(0);
	if (*s == ')')
		return pragma_allpacked = 0;

	if (*s < '0' || *s > '9') /* no number */
		return 1;
	pragma_allpacked = atoi(s);
	return eat(')');
}

static int
pragmas_renamed(char *t)
{
	char *f = pragtok(0);

	if (f == 0)
		return 1;
	pragma_renamed = newstring(f, strlen(f));
	return 0;
}

static int
pragmas_stdc(char *t)
{
	return 0; /* Just ignore */
}

struct pragmas {
	char *name;
	int (*fun)(char *);
} pragmas[] = {
	{ "pack", pragmas_pack },
	{ "packed", pragmas_alpack },
	{ "aligned", pragmas_alpack },
	{ "rename", pragmas_renamed },
#ifdef GCC_COMPAT
	{ "GCC", pragmas_gcc },
#endif
	{ "STDC", pragmas_stdc },
	{ "weak", pragmas_weak },
	{ "ident", NULL },
	{ 0 },
};

/*
 * got a full pragma line.  Split it up here.
 */
static void
pragma(void)
{
	struct pragmas *p;
	char *t, *pt;

	if ((t = pragtok(&yytext[7])) != NULL) {
		pt = ps;
		for (p = pragmas; p->name; p++) {
			if (strcmp(t, p->name) == 0) {
				if (p->fun && (*p->fun)(t))
					uerror("bad argument to #pragma");
				return;
			}
		}
		ps = pt;
		if (mypragma(t))
			return;
	}
	warner(Wunknown_pragmas, t, ps);
}

void
cunput(char c)
{
	unput(c);
}

